version: '2.9'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: kataAdmin
      POSTGRES_PASSWORD: kata123456
      PGDATA: /data/postgres
    volumes:
      - /home/jlagoria/mnt/second/dev/docker-compose/db/data-progres/:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: Shenkun1981
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
volumes:
  pgadmin: