server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    username: 'kataAdmin'
    password: 'kata123456'
    url: jdbc:postgresql://localhost:5432/fraud
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    show-sql: true
application:
  name: Fraud Service
  version: 0.0.1-SNAPSHOT